ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb-"{{env}}".cineniti.in 
CATALOGUE_HOST: catalogue-"{{env}}".cineniti.in 
REDIS_HOST: redis-"{{env}}".cineniti.in 
USER_HOST: user-"{{env}}".cineniti.in 
CART_HOST: cart-"{{env}}".cineniti.in 
MYSQL_HOST: mysql-"{{env}}".cineniti.in 
SHIPPING_HOST: shipping-"{{env}}".cineniti.in 
RABBITMQ_HOST: rabbitmq-"{{env}}".cineniti.in 
PAYMENT_HOST: payment-"{{env}}".cineniti.in 