[local]
localhost


[mongodb]
localhost

[catalogue]
localhost

[redis]
localhost

[user]
localhost

[mysql]
localhost

[cart]
localhost

[shipping]
localhost


[rabbitmq]
localhost


[payment]
localhost

[frontend]
localhost

##########








