[local]
localhost


[mongodb]
localhost

[catalogue]
catalogue-dev.cineniti.in

[redis]
localhost

[user]
user-dev.cineniti.in

[mysql]
mysql-dev.cineniti.in   

[cart]
cart-dev.cineniti.in

[shipping]
shipping-dev.cineniti.in


[rabbitmq]
rabbitmq-dev.cineniti.in


[payment]
payment-dev.cineniti.in

[frontend]
frontend-dev.cineniti.in

##########








